# Generated by Django 5.2.6 on 2025-09-10 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amenities', models.TextField(help_text='Comma separated, e.g. WiFi,Breakfast')),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('few', 'Few Rooms Left'), ('full', 'Full')], default='available', max_length=20)),
                ('location_link', models.URLField(blank=True, help_text='Google Maps link')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesthouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
