# Generated by Django 5.2.6 on 2025-09-12 07:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guesthouse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guest House', 'verbose_name_plural': 'Guest Houses'},
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='max_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='rooms_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guesthouse',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated amenities, e.g. WiFi,Breakfast,Parking'),
        ),
        migrations.AlterField(
            model_name='guesthouse',
            name='location_link',
            field=models.URLField(blank=True, help_text='Google Maps link (optional)'),
        ),
        migrations.AlterField(
            model_name='guesthouse',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
