# Generated by Django 5.2.6 on 2025-09-12 08:15

import django.db.models.deletion
import guesthouses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouses', '0002_alter_guesthouse_options_guesthouse_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse',
            name='video',
            field=models.FileField(blank=True, help_text='Optional short video showcasing the guesthouse', null=True, upload_to=guesthouses.models.guesthouse_video_upload_path),
        ),
        migrations.CreateModel(
            name='GuestHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=guesthouses.models.guesthouse_image_upload_path)),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guesthouses.guesthouse')),
            ],
        ),
    ]
