# Generated by Django 5.2.6 on 2025-09-15 04:21

import django.core.validators
import django.db.models.deletion
import guesthouses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouses', '0003_guesthouse_video_guesthouseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_rooms', models.PositiveIntegerField(default=1)),
                ('rooms_available', models.IntegerField(default=1)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities for this room type')),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='guesthouses.guesthouse')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=guesthouses.models.roomtype_image_upload_path)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guesthouses.roomtype')),
            ],
        ),
    ]
